// Shop Logo Library — 가게 대표 썸네일 로고 (44x44)
// 사용법: import { SHOP_LOGOS, getShopLogo, getRandomLogos } from "../shopLogos";

const BASE_PATH = "/assets/shop-logos/";

export const SHOP_LOGOS = [
  { id: "33tteok", name: "33떡볶이", file: "33tteok_44x44.png" },
  { id: "3cheob", name: "3첩반상", file: "3cheob_44x44.png" },
  { id: "5iljang", name: "5일장", file: "5iljang_44x44.png" },
  { id: "60gye", name: "60계치킨", file: "60gye_44x44.png" },
  { id: "7bunga", name: "7분가", file: "7bunga_44x44.png" },
  { id: "baekeok", name: "백억삼겹", file: "baekeok_44x44.png" },
  { id: "baetteok", name: "배떡", file: "baetteok_44x44.png" },
  { id: "banolim", name: "반올림피자", file: "banolim_44x44.png" },
  { id: "bareun", name: "바른치킨", file: "bareun_44x44.png" },
  { id: "bbakboy", name: "빡보이피자", file: "bbakboy_44x44.png" },
  { id: "bbq", name: "BBQ", file: "bbq_44x44.png" },
  { id: "beonjjeok", name: "번쩍치킨", file: "beonjjeok_44x44.png" },
  { id: "bhc", name: "BHC", file: "bhc_44x44.png" },
  { id: "bingsu", name: "빙수", file: "bingsu_44x44.png" },
  { id: "bodram", name: "보드람치킨", file: "bodram_44x44.png" },
  { id: "bon", name: "본도시락", file: "bon_44x44.png" },
  { id: "bongmyeong", name: "봉명동짜장", file: "bongmyeong_44x44.png" },
  { id: "bongus", name: "봉구스밥버거", file: "bongus_44x44.png" },
  { id: "bonjook", name: "본죽", file: "bonjook_44x44.png" },
  { id: "bonjookbibim", name: "본죽비빔밥", file: "bonjookbibim_44x44.png" },
  { id: "boor", name: "부어치킨", file: "boor_44x44.png" },
  { id: "boss", name: "보스치킨", file: "boss_44x44.png" },
  { id: "br", name: "배스킨라빈스", file: "br_44x44.png" },
  { id: "cafeplus", name: "카페플러스", file: "cafeplus_44x44.png" },
  { id: "caffeine", name: "카페인중독", file: "caffeine_44x44.png" },
  { id: "cheoga", name: "처갓집양념치킨", file: "cheoga_44x44.png" },
  { id: "chickenplus", name: "치킨플러스", file: "chickenplus_44x44.png" },
  { id: "coca", name: "코카", file: "coca_44x44.png" },
  { id: "compose", name: "컴포즈커피", file: "compose_44x44.png" },
  { id: "crazy", name: "크레이지카츠", file: "crazy_44x44.png" },
  { id: "crycheese", name: "크라이치즈", file: "crycheese_44x44.png" },
  { id: "ddangddang", name: "땅땅치킨", file: "ddangddang_44x44.png" },
  { id: "ddangs", name: "땅스부대찌개", file: "ddangs_44x44.png" },
  { id: "ddeokcham", name: "떡참", file: "ddeokcham_44x44.png" },
  { id: "ddobongi", name: "또봉이통닭", file: "ddobongi_44x44.png" },
  { id: "domino", name: "도미노피자", file: "domino_44x44.png" },
  { id: "dongdaemun", name: "동대문엽기떡볶이", file: "dongdaemun_44x44.png" },
  { id: "donggoong", name: "동궁찜닭", file: "donggoong_44x44.png" },
  { id: "doojjim", name: "두찜", file: "doojjim_44x44.png" },
  { id: "doredore", name: "도레도레", file: "doredore_44x44.png" },
  { id: "ediya", name: "이디야", file: "ediya_44x44.png" },
  { id: "eotang", name: "어탕", file: "eotang_44x44.png" },
  { id: "famjokbal", name: "팸족발", file: "famjokbal_44x44.png" },
  { id: "frank", name: "프랭크버거", file: "frank_44x44.png" },
  { id: "gamaro", name: "가마로강정", file: "gamaro_44x44.png" },
  { id: "gcova", name: "지코바치킨", file: "gcova_44x44.png" },
  { id: "giyoung", name: "기영이숯불두마리", file: "giyoung_44x44.png" },
  { id: "gobchang", name: "곱창고", file: "gobchang_44x44.png" },
  { id: "gongcha", name: "공차", file: "gongcha_44x44.png" },
  { id: "goobne", name: "굽네치킨", file: "goobne_44x44.png" },
  { id: "gopizza", name: "고피자", file: "gopizza_44x44.png" },
  { id: "gopuni", name: "고푸니", file: "gopuni_44x44.png" },
  { id: "granma", name: "할머니국수", file: "granma_44x44.png" },
  { id: "gukmin", name: "국민연금", file: "gukmin_44x44.png" },
  { id: "gukmul", name: "국물떡볶이", file: "gukmul_44x44.png" },
  { id: "gyegeunsang", name: "계근상", file: "gyegeunsang_44x44.png" },
  { id: "hansot", name: "한솥도시락", file: "hansot_44x44.png" },
  { id: "hosigi", name: "호식이두마리치킨", file: "hosigi_44x44.png" },
  { id: "hulala", name: "훌랄라참숯치킨", file: "hulala_44x44.png" },
  { id: "huraide", name: "후라이드참잘하는집", file: "huraide_44x44.png" },
  { id: "hwangsil", name: "황실", file: "hwangsil_44x44.png" },
  { id: "ilachi", name: "일라치", file: "ilachi_44x44.png" },
  { id: "ilmiri", name: "일미리", file: "ilmiri_44x44.png" },
  { id: "insaeng", name: "인생네컷치킨", file: "insaeng_44x44.png" },
  { id: "isaac", name: "이삭토스트", file: "isaac_44x44.png" },
  { id: "jadam", name: "자담치킨", file: "jadam_44x44.png" },
  { id: "jaws", name: "죠스떡볶이", file: "jaws_44x44.png" },
  { id: "jeyookwang", name: "제육왕", file: "jeyookwang_44x44.png" },
  { id: "jimmy", name: "지미존스", file: "jimmy_44x44.png" },
  { id: "kfc", name: "KFC", file: "kfc_44x44.png" },
  { id: "kim", name: "김밥천국", file: "kim_44x44.png" },
  { id: "kimsabu", name: "김사부", file: "kimsabu_44x44.png" },
  { id: "kimteacher", name: "김선생", file: "kimteacher_44x44.png" },
  { id: "king", name: "킹콩부대찌개", file: "king_44x44.png" },
  { id: "kkuburako", name: "꾸브라꼬", file: "kkuburako_44x44.png" },
  { id: "kyochon", name: "교촌치킨", file: "kyochon_44x44.png" },
  { id: "localfavorite", name: "동네맛집", file: "localfavorite_44x44.png" },
  { id: "longs", name: "롱스", file: "longs_44x44.png" },
  { id: "lotte", name: "롯데리아", file: "lotte_44x44.png" },
  { id: "mara", name: "마라탕", file: "mara_44x44.png" },
  { id: "market", name: "마켓컬리", file: "market_44x44.png" },
  { id: "mawang", name: "마왕족발", file: "mawang_44x44.png" },
  { id: "mcdonalds", name: "맥도날드", file: "mcdonalds_44x44.png" },
  { id: "mexicana", name: "멕시카나", file: "mexicana_44x44.png" },
  { id: "mgc", name: "메가커피", file: "mgc_44x44.png" },
  { id: "moms", name: "맘스터치", file: "moms_44x44.png" },
  { id: "momspizza", name: "맘스피자앤치킨", file: "momspizza&chiken_44x44.png" },
  { id: "mrpizza", name: "미스터피자", file: "mrpizza_44x44.png" },
  { id: "myeograng", name: "며그랑", file: "myeograng_44x44.png" },
  { id: "naeng", name: "냉면", file: "naeng_44x44.png" },
  { id: "nene", name: "네네치킨", file: "nene_44x44.png" },
  { id: "newyork", name: "뉴욕야시장", file: "newyork_44x44.png" },
  { id: "no", name: "노브랜드버거", file: "no_44x44.png" },
  { id: "nomore", name: "노모어피자", file: "nomore_44x44.png" },
  { id: "noodlestree", name: "면의전쟁", file: "noodlestree_44x44.png" },
  { id: "norang", name: "노랑통닭", file: "norang_44x44.png" },
  { id: "nyam", name: "냠냠", file: "nyam_44x44.png" },
  { id: "ourgranma", name: "우리할매떡볶이", file: "ourgranma_44x44.png" },
  { id: "oven", name: "오븐마루", file: "oven_44x44.png" },
  { id: "papajohns", name: "파파존스", file: "papajohns_44x44.png" },
  { id: "paris", name: "파리바게뜨", file: "paris_44x44.png" },
  { id: "paul", name: "폴바셋", file: "paul_44x44.png" },
  { id: "pelicana", name: "페리카나", file: "pelicana_44x44.png" },
  { id: "pinachigong", name: "피나치공", file: "pinachigong_44x44.png" },
  { id: "pizzahut", name: "피자헛", file: "pizzahut_44x44.png" },
  { id: "poke", name: "포케", file: "poke_44x44.png" },
  { id: "puradak", name: "푸라닭", file: "puradak__44x44.png" },
  { id: "salady", name: "샐러디", file: "salady_44x44.png" },
  { id: "sangmu", name: "상무초밥", file: "sangmu_44x44.png" },
  { id: "school", name: "스쿨푸드", file: "school_44x44.png" },
  { id: "shake", name: "쉐이크쉑", file: "shake_44x44.png" },
  { id: "sinjeon", name: "신전떡볶이", file: "sinjeon_44x44.png" },
  { id: "subway", name: "서브웨이", file: "subway_44x44.png" },
  { id: "sulbing", name: "설빙", file: "sulbing_44x44.png" },
  { id: "supercrispy", name: "슈퍼크리스피", file: "supercrispy_44x44.png" },
  { id: "tangsuyuk", name: "탕수육", file: "tangsuyuk_44x44.png" },
  { id: "tiba", name: "티바두마리치킨", file: "tiba_44x44.png" },
  { id: "tim", name: "팀호완", file: "tim_44x44.png" },
  { id: "tmppizza", name: "TMP피자", file: "TMPpizza_44x44.png" },
  { id: "toping", name: "토핑", file: "toping_44x44.png" },
  { id: "tousles", name: "뚜레쥬르", file: "tousles_44x44.png" },
  { id: "ttorae", name: "또래오래", file: "ttorae_44x44.png" },
  { id: "twosome", name: "투썸플레이스", file: "twosome_44x44.png" },
  { id: "uga", name: "우가네", file: "uga_44x44.png" },
  { id: "um", name: "엄마손도시락", file: "um_44x44.png" },
  { id: "venti", name: "벤티", file: "venti_44x44.png" },
  { id: "waffle", name: "와플대학", file: "waffle_44x44.png" },
  { id: "what", name: "왓떡", file: "what_44x44.png" },
  { id: "yamsam", name: "얌샘김밥", file: "yamsam_44x44.png" },
  { id: "yeoljeong", name: "열정도", file: "yeoljeong_44x44.png" },
  { id: "yoajung", name: "요아정", file: "yoajung_44x44.png" },
  { id: "young", name: "영광보리굴비", file: "young_44x44.png" },
  { id: "youngman", name: "청년피자", file: "youngman_44x44.png" },
];

// ID로 로고 가져오기
export function getShopLogo(id) {
  const logo = SHOP_LOGOS.find(l => l.id === id);
  return logo ? BASE_PATH + logo.file : null;
}

// 이름으로 로고 가져오기
export function getShopLogoByName(name) {
  const logo = SHOP_LOGOS.find(l => l.name === name);
  return logo ? BASE_PATH + logo.file : null;
}

// 랜덤 N개 로고 가져오기 (컴포넌트 미리보기용)
export function getRandomLogos(count = 5) {
  const shuffled = [...SHOP_LOGOS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(l => ({
    ...l,
    url: BASE_PATH + l.file,
  }));
}

// 전체 로고 URL 포함
export function getAllLogos() {
  return SHOP_LOGOS.map(l => ({
    ...l,
    url: BASE_PATH + l.file,
  }));
}
